---
  - id: generate-readme
    name: Home Assistant README Generator
    description: generate a README for the Home Assistant packages
    entry: generate-readme
    language: python
    args: []
    always_run: true
    require_serial: true
    pass_filenames: false

  - id: validate-entities
    name: Home Assistant Core Configuration Validator
    description: Validate the Home Assistant entities directory
    entry: validate-entities
    language: python
    args: []
    always_run: true
    require_serial: true
    pass_filenames: false

  - id: validate-lovelace
    name: Home Assistant Lovelace Configuration Validator
    description: Validate the Home Assistant Lovelace configuration
    entry: validate-lovelace
    language: python
    args: []
    always_run: true
    require_serial: true
    pass_filenames: false
